version: '3.9'

services:
  proxy:
    container_name: proxy
    restart: always
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./resources/certs:/etc/nginx/certs

  proxy-companion:        
    container_name: proxy-companion
    restart: always
    image: sebastienheyd/self-signed-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./resources/certs:/etc/nginx/certs
  janus-web:
    image: nginx:latest
    ports:
      - "8080:8080"
    links:
      - janus-gateway
    depends_on: 
      - "proxy" 
      - "proxy-companion"
      - "janus-gateway"
    volumes:
      - ./data/html:/usr/share/nginx/html
      - ./resources/web/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      VIRTUAL_HOST: 192.168.1.9
      SELF_SIGNED_HOST: 192.168.1.9
  janus-gateway:
    image: 'canyan/janus-gateway:latest'
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    ports:
      - "8188:8188"
      - "8088:8088"
      - "8089:8089"
      - "8889:8889"
      - "8000:8000"
      - "7088:7088"
      - "7089:7089"
    volumes:
      - "./resources/janus/janus.jcfg:/usr/local/etc/janus/janus.jcfg"
      - "./resources/janus/janus.eventhandler.sampleevh.jcfg:/usr/local/etc/janus/janus.eventhandler.sampleevh.jcfg"
    restart: always